import com.meli.ui.controllers.GreetController;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        new GreetController().greet();
    }
}
