/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.meli.ui.controllers.GreetController;
import com.meli.ui.presenters.GreetPresenter;
import org.junit.Test;
import static org.junit.Assert.*;

public class GreetTest {
    @Test public void testAppHasAGreeting() {
        GreetController classUnderTest = new GreetController();
    }
}
